### ISSUE TITLE
onAdd counter?

### ISSUE THREAD

**Issue by gleenk** [jenwachter/jquery.repeatable#4]
Hi guys, how can i use onAdd callback to make a counter (to see row 1 etc?)? 
Is there something to edit only added element and not altering everything?

**Comment by jenwachter** [comment]
Use the onAdd callback as such:
```js
$("form .repeatable-container").repeatable({
  onAdd: function () {
    console.log("test");
  }
});
```
You can use that function to increase a counter that you create.

I don't really understand what you mean by "edit only added element and not altering everything," but it sounds to me like you need to use a more specific jQuery selector.

**Comment by gleenk** [comment]
I did it using another function, called onAdd

`function countRow(){
	contatore = 1;
	$(".repeatable-order-row").each(function(){
		$("legend span", this).text(contatore++);
	});
}`
