### ISSUE TITLE
Get id of the added row

### ISSUE THREAD

**Issue by vasikgreif** [jenwachter/jquery.repeatable#8]
Hello,
thanks for a great plugin. Is there any way to get ID of the added row? I need to prefill some values to the row that was added. I tried to use something like:

```
$(".repeatable-container").repeatable({
        template: "#people",
        afterAdd: function(el) {
            console.log(el);
        }
    });
```

but the `el` is `undefined`

Thanks

**Comment by jenwachter** [comment]
`el` is undefined because the `afterAdd` callback does not have any passed arguments. It's a good idea though, so I've added this in the [latest release](https://github.com/jenwachter/jquery.repeatable/releases/tag/v0.4).
